name: Faturas ANP
on:
  schedule:
    - cron: '0 5 * * 1-5'  # Segunda a sexta às 5h UTC (2h BRT)
  workflow_dispatch:

jobs:
  scrape-faturas:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4
        
    - name: Run faturas scraper
      run: python src/faturas.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github_anp@outlook.com"
        git config --local user.name "GitHub ANP Automation"
        git add data/faturas.json
        git commit -m "📦 Faturas Update: $(date +'%Y-%m-%d %H:%M')" || echo "Sem alterações para commit"
        git push
